# Generated by Django 2.1.7 on 2020-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200808_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Close_Price',
            new_name='Face_Price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='High',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Last_Price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Low',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Open_Price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Volume',
        ),
        migrations.AddField(
            model_name='category',
            name='Amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Current_Price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Debi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Down_Price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='DungRak',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='High_Price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Low_Price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Per',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Prev_Price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Start_Price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Trade_Money',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Trade_Volume',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='UP_Price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Week_52_High',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Week_52_Low',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
